"""
Visualize cp-hard UMAP split outputs.

Expected input parquet columns:
- target_uniprot_id
- is_train
- umap_x
- umap_y
- split (optional)

Outputs two figures:
1) actual `is_train` assignment from cp-hard optimization
2) random baseline assignment with train ratio = 0.8 (deterministic by seed)
"""

from __future__ import annotations

import argparse
import os
import importlib
from typing import Any

pl = importlib.import_module("polars")

np = importlib.import_module("numpy")


def _build_random_mask(n: int, train_frac: float, seed: int) -> Any:
    rng = np.random.default_rng(seed)
    n_train = int(n * train_frac)
    idx = np.arange(n)
    rng.shuffle(idx)
    mask = np.zeros(n, dtype=bool)
    mask[idx[:n_train]] = True
    return mask


def _plot_assignment(
    x: Any,
    y: Any,
    is_train: Any,
    title: str,
    out_path: str,
) -> None:
    try:
        plt = importlib.import_module("matplotlib.pyplot")
    except ImportError as e:
        raise ImportError("matplotlib is required to plot UMAP visualizations.") from e

    fig, ax = plt.subplots(figsize=(8, 6), dpi=160)

    ax.scatter(
        x[~is_train],
        y[~is_train],
        s=5,
        alpha=0.65,
        # c="#9aa0a6",
        c = "#ff7f0e",
        label="non-train",
        linewidths=0,
    )
    ax.scatter(
        x[is_train],
        y[is_train],
        s=5,
        alpha=0.8,
        c="#1f77b4",
        label="train",
        linewidths=0,
    )

    ax.set_title(title)
    ax.set_xlabel("UMAP-1")
    ax.set_ylabel("UMAP-2")
    ax.legend(loc="best")
    fig.tight_layout()

    fig.savefig(out_path)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Visualize cp-hard UMAP split assignments.")
    parser.add_argument(
        "--input",
        type=str,
        default=os.path.join("data", "cp_hard_umap_seed42.parquet"),
        help="Path to UMAP split parquet generated by split_utils.py",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="data",
        help="Directory to save output figures",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Seed for random baseline assignment",
    )
    parser.add_argument(
        "--train_frac",
        type=float,
        default=0.8,
        help="Train ratio for random baseline",
    )
    args = parser.parse_args()

    df = pl.read_parquet(args.input)

    required = {"umap_x", "umap_y", "is_train"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns in input parquet: {sorted(missing)}")

    x = np.asarray(df["umap_x"].to_list(), dtype=np.float32)
    y = np.asarray(df["umap_y"].to_list(), dtype=np.float32)
    actual_train = np.asarray(df["is_train"].to_list(), dtype=bool)

    random_train = _build_random_mask(len(df), train_frac=args.train_frac, seed=args.seed)

    os.makedirs(args.output_dir, exist_ok=True)

    out_actual = os.path.join(args.output_dir, "umap_is_train.png")
    out_random = os.path.join(args.output_dir, "umap_random_0.8_train.png")

    _plot_assignment(
        x,
        y,
        actual_train,
        title="UMAP: cp-hard optimized split (is_train)",
        out_path=out_actual,
    )
    _plot_assignment(
        x,
        y,
        random_train,
        title="UMAP: random split baseline (train=0.8)",
        out_path=out_random,
    )

    print(f"Saved figure: {out_actual}")
    print(f"Saved figure: {out_random}")


if __name__ == "__main__":
    main()
